CREATE TABLE IF NOT EXISTS leads (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(120) NULL,
  source VARCHAR(80) NOT NULL DEFAULT 'unknown',
  status VARCHAR(40) NOT NULL DEFAULT 'new',
  assigned_to VARCHAR(120) NULL,
  notes TEXT NULL,
  follow_up_at DATETIME NULL,
  last_call_outcome VARCHAR(255) NULL,
  last_called_at DATETIME NULL,
  last_message TEXT NULL,
  last_message_at DATETIME NULL,
  raw_payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_assigned_to (assigned_to),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
